<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Travaling.Master" CodeBehind="foodpage.aspx.vb" Inherits="Takcity.foodpage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <div style="margin:50px 50px 50px 125px; padding-right:50px; padding-left: 0px; padding-top: 0px; padding-bottom: 0px;">
    <h1 align="center" style="color:white;">ร้านอาหารจังหวัดตาก</h1>
        <
        <br /><br />
        <h1 align="center" style="color:aliceblue; font-size:26px;">1.ร้าน บ.กุ้งเผา</h1>
        <br /><br />
        <img src="https://img.wongnai.com/p/624x0/2021/04/12/1f14745d1fc447b7a1cd6117c529b44a.jpg" class="img"/>
        <br /><br />
        <p class="paper">“ร้านอาหารตากเจ้าดังที่มีชื่อเสียงในเรื่องของทะเลสด ๆ ส่งตรงมาจากฝั่งพม่า ของที่ต้องห้ามพลาดของร้านนี้คือ “กุ้ง” ได้สั่งมาหลายอย่างทั้ง “ข้าวผัดกุ้ง” ที่ผัดมาแห้งดี กุ้งตัวเล็กหน่อย แต่สดใช้ได้เลย “หอยนางรมสด” 
            ใหญ่ สด หวาน และไม่คาวเลย และทีเด็ด “กุ้งเผา” สดสมคำร่ำลือจริง ๆ ในเรื่องของราคาก็ถือว่าเหมาะสมกับทั้งรสชาติและคุณภาพที่ได้รับ แนะนำเลยสำหรับใครที่มาเที่ยวแถบแม่สอด” (โดยคุณ Toeyy.) 
            

        <p class="paper">&nbsp;<p class="paper"><span style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: 
    Poppins, sans-serif; text-decoration: none; list-style: none; color: rgb(255, 255, 255); font-size: 16px; font-style: normal; 
                         font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; 
                         text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; 
                         white-space: normal; background-color: rgb(34, 35, 39);">📞</span><strong style="padding: 0px; margin: 0px; box-sizing: border-box; 
font-family: Poppins, sans-serif; text-decoration: none; list-style: none; color: rgb(255, 255, 255); font-size: 16px; font-style: normal; 
font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(34, 35, 39);"><span style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none;">&nbsp;</span><span lang="TH" style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none;">โทรศัพท์</span><span style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none;">&nbsp;:&nbsp;</span></strong><span style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none; color: rgb(255, 255, 255); font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(34, 35, 39);">095-712-7637<br style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none;" />
        🔬</span><strong style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none; color: rgb(255, 255, 255); font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(34, 35, 39);"><span style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none;">&nbsp;Facebook&nbsp;:</span></strong><span style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none; color: rgb(255, 255, 255); font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(34, 35, 39);">&nbsp;<a href="https://www.facebook.com/borkungpaomaesot/?locale=th_TH">บ้านกุ้งเผา</a><br style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none;" />
        🌎</span><strong style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none; color: rgb(255, 255, 255); font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(34, 35, 39);"><span style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none;">&nbsp;Google Map&nbsp; :</span></strong><span style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none; color: rgb(255, 255, 255); font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(34, 35, 39);">&nbsp;<a href="https://goo.gl/maps/iAKyMZ95UNuFxAzH9" style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none;" target="_blank"><a href="https://maps.app.goo.gl/anz4sQGHMMVdPSYs9">https://maps.app.goo.gl/anz4sQGHMMVdPSYs9</a></a></span>
            
    <br /><br />
    <h1 align="center" style="color:white;font-size:26px;">2.เถียงนาคอฟฟี่</h1>
    <br /><br />
    <img src="https://img.wongnai.com/p/624x0/2022/03/04/39f9879d9a2647d2a26450e3761e97fc.jpg" class="img" />
            <br /><br />
            <p class="paper">ร้านอาหารตากชื่อบ้าน ๆ เข้าถึงง่าย ว่า เถียงนา เพราะร้านสไตล์ไม้ ๆ แต่ใหญ่โตมีบริเวณ ขายขนมเบเกอรี ของขึ้นชื่อคือ ครัวซองต์แบบต่าง ๆ ก็เลยต้องมาจัดการสักกะหน่อยครับ ร้านจัดสไตล์สวน ๆ
                เขียวสบายตา เป็นเถียงนาโรงนาโล่ง ๆ มีหลายโซน โซนโอเพ่น โซนในสวน โซนนั่งชมธรรมชาติ มีเยอะ เดินเข้ามาหอมเบเกอรีมากครับ ลูกค้ามีพอสมควรนั่งพักผ่อนตามโซนที่นั่งที่ตัวเองเลือกดูสบายใจ วันนี้ซื้อขนมหลายชิ้น 
                เอาไปกินระหว่างทางครับ หอม อร่อย เลียมือ สมยี่ห้อร้านมีรางวัลครับผม  ขนมมีเพียบเลยนะ Croissant Fudgy Chocolate Cake Blueberry Cheese Pie ครัวซองต์อัลมอนด์ Chocolate signature” (โดยคุณ Pipatpong Promchan) 
            <p class="paper">&nbsp;<p class="paper"><span style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none; color: rgb(255, 255, 255); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; font-size: 16px; background-color: rgb(34, 35, 39);">📞</span><strong style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none; color: rgb(255, 255, 255); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; font-size: 16px; background-color: rgb(34, 35, 39);"><span style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none;">&nbsp;</span><span lang="TH" style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none;">โทรศัพท์</span><span style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none;">&nbsp;:&nbsp;</span></strong><span style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none; color: rgb(255, 255, 255); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; font-size: 16px; background-color: rgb(34, 35, 39);">064-819-7658<br style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none;" />
        🔬</span><strong style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none; color: rgb(255, 255, 255); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; font-size: 16px; background-color: rgb(34, 35, 39);"><span style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none;">&nbsp;Facebook&nbsp;:</span></strong><span style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none; color: rgb(255, 255, 255); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; font-size: 16px; background-color: rgb(34, 35, 39);">&nbsp;<a href="https://www.facebook.com/borkungpaomaesot/?locale=th_TH" style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none;">เถียงนา</a><br style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none;" />
        🌎</span><strong style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none; color: rgb(255, 255, 255); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; font-size: 16px; background-color: rgb(34, 35, 39);"><span style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none;">&nbsp;Google Map&nbsp; :</span></strong><span style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none; color: rgb(255, 255, 255); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; font-size: 16px; background-color: rgb(34, 35, 39);">&nbsp;<a href="https://goo.gl/maps/iAKyMZ95UNuFxAzH9" style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none;" target="_blank"></a><a href="https://maps.app.goo.gl/anz4sQGHMMVdPSYs9" style="padding: 0px; margin: 0px; box-sizing: border-box; font-family: Poppins, sans-serif; text-decoration: none; list-style: none;"><a href="https://maps.app.goo.gl/X3rneaqKUa4JbXyKA">https://maps.app.goo.gl/X3rneaqKUa4JbXyKA</a></a></span></div>
</asp:Content>